export const GAME_STATES = {
  PLAYING: 'PLAYING',
  WINNING: 'WINNING',
  GAME_OVER: 'GAME_OVER',
  IDLE: 'IDLE'
};

export const GAME_CONFIG = {
  COUNTDOWN_DURATION: 3.0,
  COUNTDOWN_INTERVAL: 100,
  COUNTDOWN_STEP: 0.1,
  AUTOPLAY_INTERVAL: 2000,
  TIME_INTERVAL: 100,
  TIME_STEP: 0.1
};

export const GAME_STATUS = {
  [GAME_STATES.WINNING]: 'ALL CLEAR',
  [GAME_STATES.GAME_OVER]: 'GAME OVER',
  [GAME_STATES.IDLE]: 'LET\'S PLAY',
  [GAME_STATES.PLAYING]: 'LET\'S PLAY'
}; 